apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
      - name: my-node-app
        imagePullPolicy: IfNotPresent
        image: 'arjun164/zeecart-node-app:v4'
        ports:
        - containerPort: 4000
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: my-node-app-service
spec:
  selector: 
    app: my-node-app
  ports: 
  - name: http
    port: 4000
    targetPort: 4000
  type: NodePort